# Generated by Django 5.0.6 on 2025-11-28 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='league.conference')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('conference', 'name')},
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conference_count', models.PositiveIntegerField(default=2)),
                ('division_count_per_conference', models.PositiveIntegerField(default=4)),
                ('teams_per_division', models.PositiveIntegerField(default=4)),
                ('free_agency_mode', models.CharField(choices=[('auction', 'Auction'), ('rounds', 'RoundBased')], default='auction', max_length=20)),
                ('allow_cap_growth', models.BooleanField(default=False)),
                ('allow_playoff_expansion', models.BooleanField(default=False)),
                ('enable_realignment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='league.league'),
        ),
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('league', 'name')},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=5)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='league.conference')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='league.division')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.league')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['league_id', 'abbreviation'],
                'unique_together': {('league', 'abbreviation')},
            },
        ),
    ]
