# Generated by Django 5.0.6 on 2025-11-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_season_week_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_size_limit',
            field=models.PositiveIntegerField(default=53),
        ),
        migrations.AddField(
            model_name='league',
            name='salary_cap',
            field=models.DecimalField(decimal_places=2, default=200000000.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('LB', 'Linebacker'), ('CB', 'Cornerback'), ('S', 'Safety'), ('K', 'Kicker'), ('P', 'Punter')], max_length=3)),
                ('age', models.PositiveIntegerField(default=21)),
                ('height_inches', models.PositiveIntegerField(default=72)),
                ('weight_lbs', models.PositiveIntegerField(default=200)),
                ('overall_rating', models.PositiveIntegerField(default=60)),
                ('potential_rating', models.PositiveIntegerField(default=70)),
                ('injury_status', models.CharField(default='healthy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='league.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('years', models.PositiveIntegerField(default=1)),
                ('start_year', models.PositiveIntegerField(default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='league.team')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='league.player')),
            ],
            options={
                'ordering': ['team_id', 'player_id'],
            },
        ),
    ]
