# Generated by Django 5.0.6 on 2025-11-28 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('league.create', 'League Created'), ('team.create', 'Team Created'), ('roster.add', 'Roster Add'), ('roster.release', 'Roster Release'), ('league.schedule.generate', 'Schedule Generated'), ('trade.create', 'Trade Created'), ('trade.accept', 'Trade Accepted'), ('trade.reverse', 'Trade Reversed')], max_length=50),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('reversed', 'Reversed'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_out', to='league.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='league.league')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_in', to='league.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items_from', to='league.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items_to', to='league.team')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='league.trade')),
            ],
            options={
                'unique_together': {('trade', 'player')},
            },
        ),
    ]
