# Generated by Django 5.0.6 on 2025-11-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_auditlog_action_trade_tradeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('league.create', 'League Created'), ('team.create', 'Team Created'), ('roster.add', 'Roster Add'), ('roster.release', 'Roster Release'), ('league.schedule.generate', 'Schedule Generated'), ('trade.create', 'Trade Created'), ('trade.accept', 'Trade Accepted'), ('trade.reverse', 'Trade Reversed'), ('waiver.release', 'Waiver Release'), ('waiver.claim', 'Waiver Claim')], max_length=50),
        ),
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awarded', 'Awarded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waivers_in', to='league.team')),
                ('from_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waivers_out', to='league.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims', to='league.league')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claim', to='league.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
