# Generated by Django 5.0.6 on 2025-11-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_auditlog_action_waiverclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('league.create', 'League Created'), ('team.create', 'Team Created'), ('roster.add', 'Roster Add'), ('roster.release', 'Roster Release'), ('league.schedule.generate', 'Schedule Generated'), ('trade.create', 'Trade Created'), ('trade.accept', 'Trade Accepted'), ('trade.reverse', 'Trade Reversed'), ('waiver.release', 'Waiver Release'), ('waiver.claim', 'Waiver Claim'), ('contract.update', 'Contract Update')], max_length=50),
        ),
    ]
