# Generated by Django 5.0.6 on 2025-11-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_game_loser_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('league.create', 'League Created'), ('league.update', 'League Updated'), ('team.create', 'Team Created'), ('roster.add', 'Roster Add'), ('roster.release', 'Roster Release'), ('league.schedule.generate', 'Schedule Generated'), ('trade.create', 'Trade Created'), ('trade.accept', 'Trade Accepted'), ('trade.reverse', 'Trade Reversed'), ('waiver.release', 'Waiver Release'), ('waiver.claim', 'Waiver Claim'), ('contract.update', 'Contract Update'), ('draft.create', 'Draft Created'), ('draft.pick', 'Draft Pick Made'), ('game.complete', 'Game Completed')], max_length=50),
        ),
    ]
