# Generated by Django 5.0.6 on 2025-11-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_auditlog_action_delete_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium_capacity',
            field=models.PositiveIntegerField(default=60000),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_turf',
            field=models.CharField(choices=[('grass', 'Grass'), ('turf', 'Turf'), ('hybrid', 'Hybrid')], default='grass', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_weather',
            field=models.CharField(choices=[('temperate', 'Temperate'), ('cold', 'Cold'), ('dome', 'Dome'), ('extreme', 'Extreme')], default='temperate', max_length=20),
        ),
    ]
