# Generated by Django 5.0.6 on 2025-12-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_player_is_rookie_pool_player_league_freeagencybid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeagencybid',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeagencybid',
            name='mode',
            field=models.CharField(default='auction', max_length=20),
        ),
        migrations.AddField(
            model_name='freeagencybid',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('league.create', 'League Created'), ('league.update', 'League Updated'), ('league.delete', 'League Deleted'), ('team.create', 'Team Created'), ('team.delete', 'Team Deleted'), ('roster.add', 'Roster Add'), ('roster.release', 'Roster Release'), ('league.schedule.generate', 'Schedule Generated'), ('trade.create', 'Trade Created'), ('trade.accept', 'Trade Accepted'), ('trade.reverse', 'Trade Reversed'), ('waiver.release', 'Waiver Release'), ('waiver.claim', 'Waiver Claim'), ('fa.bid', 'Free Agency Bid'), ('fa.award', 'Free Agency Award'), ('contract.update', 'Contract Update'), ('draft.create', 'Draft Created'), ('draft.pick', 'Draft Pick Made'), ('game.complete', 'Game Completed')], max_length=50),
        ),
    ]
