# Generated by Django 5.0.6 on 2025-12-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_freeagencybid_expires_at_freeagencybid_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='freeagencybid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
