# Generated by Django 5.0.6 on 2025-12-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_notification_category_alter_freeagencybid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByeWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byes', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byes', to='league.team')),
            ],
            options={
                'ordering': ['season_id', 'week_number', 'team_id'],
                'unique_together': {('season', 'team', 'week_number')},
            },
        ),
    ]
