# Generated by Django 5.0.6 on 2025-12-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_add_ir_and_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating_accel',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_agility',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_discipline',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_endurance',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_hands',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_intelligence',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_speed',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='rating_strength',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='PlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_index', models.PositiveIntegerField()),
                ('quarter', models.PositiveIntegerField(default=1)),
                ('clock_seconds', models.PositiveIntegerField(default=900)),
                ('summary', models.CharField(max_length=255)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='league.game')),
            ],
            options={
                'ordering': ['game_id', 'play_index'],
            },
        ),
        migrations.CreateModel(
            name='TeamGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_yards', models.IntegerField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='league.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='league.team')),
            ],
            options={
                'ordering': ['game_id', 'team_id'],
                'unique_together': {('game', 'team')},
            },
        ),
    ]
