from django.urls import path

from .views import (
    ContractUpdateView,
    DraftCreateView,
    DraftDetailView,
    DraftPickSelectView,
    StandingsView,
    GameCompleteView,
    PlayoffSeedingView,
    PlayoffBracketView,
    RookiePoolGenerateView,
    RookiePoolListView,
    FreeAgentListView,
    FreeAgencyBidView,
    FreeAgencyResolveView,
    InjuryListCreateView,
    InjuryResolveView,
    NotificationListView,
    NotificationMarkReadView,
    LeagueDetailView,
    LeagueListCreateView,
    LeagueStructureView,
    LeagueUpdateView,
    LeagueDeleteView,
    ConferenceRenameView,
    DivisionRenameView,
    SeasonGenerateView,
    SeasonScheduleView,
    GameCompleteView,
    TradeAcceptView,
    TradeListCreateView,
    TradeReverseView,
    WaiverClaimView,
    WaiverListView,
    WaiverReleaseView,
    TeamRosterReleaseView,
    TeamRosterCreateView,
    TeamRosterView,
    TeamCreateView,
    TeamDeleteView,
    TeamListView,
)

app_name = "league"

urlpatterns = [
    path("leagues/", LeagueListCreateView.as_view(), name="league-list-create"),
    path("leagues/<int:pk>/", LeagueDetailView.as_view(), name="league-detail"),
    path("leagues/<int:pk>/update/", LeagueUpdateView.as_view(), name="league-update"),
    path("leagues/<int:pk>/delete/", LeagueDeleteView.as_view(), name="league-delete"),
    path(
        "leagues/<int:league_id>/conferences/<int:conf_id>/rename/",
        ConferenceRenameView.as_view(),
        name="conference-rename",
    ),
    path(
        "leagues/<int:league_id>/divisions/<int:div_id>/rename/",
        DivisionRenameView.as_view(),
        name="division-rename",
    ),
    path("leagues/<int:pk>/structure/", LeagueStructureView.as_view(), name="league-structure"),
    path("leagues/<int:league_id>/drafts/", DraftCreateView.as_view(), name="draft-create"),
    path("drafts/<int:pk>/", DraftDetailView.as_view(), name="draft-detail"),
    path("drafts/picks/<int:pk>/select/", DraftPickSelectView.as_view(), name="draft-pick-select"),
    path("leagues/<int:league_id>/seasons/generate/", SeasonGenerateView.as_view(), name="season-generate"),
    path(
        "leagues/<int:league_id>/seasons/<int:year>/schedule/",
        SeasonScheduleView.as_view(),
        name="season-schedule",
    ),
    path("leagues/<int:league_id>/seasons/<int:year>/standings/", StandingsView.as_view(), name="standings"),
    path("leagues/<int:league_id>/seasons/<int:year>/seeds/", PlayoffSeedingView.as_view(), name="playoff-seeds"),
    path("leagues/<int:league_id>/seasons/<int:year>/bracket/", PlayoffBracketView.as_view(), name="playoff-bracket"),
    path("leagues/<int:league_id>/drafts/rookies/generate/", RookiePoolGenerateView.as_view(), name="rookie-generate"),
    path("leagues/<int:league_id>/drafts/rookies/", RookiePoolListView.as_view(), name="rookie-list"),
    path("leagues/<int:league_id>/free_agents/", FreeAgentListView.as_view(), name="free-agent-list"),
    path("leagues/<int:league_id>/free_agents/bids/", FreeAgencyBidView.as_view(), name="free-agent-bid"),
    path("leagues/<int:league_id>/free_agents/resolve/", FreeAgencyResolveView.as_view(), name="free-agent-resolve"),
    path("leagues/<int:league_id>/injuries/", InjuryListCreateView.as_view(), name="injury-list-create"),
    path("injuries/<int:pk>/resolve/", InjuryResolveView.as_view(), name="injury-resolve"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationMarkReadView.as_view(), name="notification-read"),
    path("games/<int:pk>/complete/", GameCompleteView.as_view(), name="game-complete"),
    path("games/<int:pk>/complete/", GameCompleteView.as_view(), name="game-complete"),
    path("leagues/<int:league_id>/trades/", TradeListCreateView.as_view(), name="trade-list-create"),
    path("trades/<int:pk>/accept/", TradeAcceptView.as_view(), name="trade-accept"),
    path("trades/<int:pk>/reverse/", TradeReverseView.as_view(), name="trade-reverse"),
    path("leagues/<int:league_id>/waivers/", WaiverListView.as_view(), name="waiver-list"),
    path("leagues/<int:league_id>/waivers/release/", WaiverReleaseView.as_view(), name="waiver-release"),
    path("waivers/<int:pk>/claim/", WaiverClaimView.as_view(), name="waiver-claim"),
    path("leagues/<int:league_id>/contracts/<int:player_id>/", ContractUpdateView.as_view(), name="contract-update"),
    path("leagues/<int:league_id>/teams/", TeamListView.as_view(), name="team-list"),
    path("leagues/<int:league_id>/teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("leagues/<int:league_id>/teams/<int:team_id>/roster/", TeamRosterView.as_view(), name="team-roster"),
    path(
        "leagues/<int:league_id>/teams/<int:team_id>/roster/add/",
        TeamRosterCreateView.as_view(),
        name="team-roster-add",
    ),
    path(
        "leagues/<int:league_id>/teams/<int:team_id>/roster/<int:player_id>/release/",
        TeamRosterReleaseView.as_view(),
        name="team-roster-release",
    ),
    path("leagues/<int:league_id>/teams/<int:team_id>/delete/", TeamDeleteView.as_view(), name="team-delete"),
]
